In [1]:
import pandas as pd
import autogen
import re
from tqdm import tqdm

# 1. Setup LLM Lokal (Ollama)
local_llm_setup = {
    "config_list": [
        {
            "model": "llama3",
            "base_url": "http://localhost:11434/v1",
            "api_key": "dummy-key-ollama" # Wajib ada format api_key
        }
    ],
    "temperature": 0.1
}

# 2. Agen Pertama: Penilai Utama
agent_assessor = autogen.AssistantAgent(
    name="Primary_Assessor",
    system_message="""Anda bertugas sebagai Guru Evaluator. Baca esai yang diberikan, berikan ringkasan evaluasi (maksimal 3 kalimat) terkait kelancaran bahasa dan substansi. 
    Di akhir kalimat, sebutkan estimasi skor dari skala 1 sampai 6.""",
    llm_config=local_llm_setup,
)

# 3. Agen Kedua: Pengambil Keputusan
agent_final_judge = autogen.AssistantAgent(
    name="Final_Judge",
    system_message="""Peran Anda adalah Kepala Penilai. Analisis argumen dari Primary_Assessor. 
    Anda bebas setuju atau tidak. KETENTUAN WAJIB: Balasan Anda HANYA boleh berisi SATU KARAKTER ANGKA (1, 2, 3, 4, 5, atau 6) yang merepresentasikan skor mutlak. Jangan tambahkan kata apapun.""",
    llm_config=local_llm_setup,
)

# 4. Agen Ketiga: Koordinator Diskusi
agent_coordinator = autogen.UserProxyAgent(
    name="Coordinator",
    human_input_mode="NEVER", 
    max_consecutive_auto_reply=1,
    code_execution_config=False,
    is_termination_msg=lambda msg: "TERMINATE" in msg.get("content", "")
)

print("Semua agen AI siap beroperasi!")

Semua agen AI siap beroperasi!

In [2]:
def execute_agent_debate(essay_content):
    # Reset memori obrolan agar agen tidak tercampur dengan esai sebelumnya
    agent_coordinator.clear_history()
    agent_assessor.clear_history()
    agent_final_judge.clear_history()
    
    # Inisiasi wadah diskusi
    discussion_forum = autogen.GroupChat(
        agents=[agent_coordinator, agent_assessor, agent_final_judge], 
        messages=[], 
        max_round=3 # Alur: Coordinator -> Assessor -> Final Judge
    )
    
    chat_manager = autogen.GroupChatManager(groupchat=discussion_forum, llm_config=local_llm_setup)
    
    # Perintah awal
    prompt_task = f"Mohon berikan evaluasi dan skor untuk esai berikut: \n\n{essay_content}"
    
    # Eksekusi obrolan
    agent_coordinator.initiate_chat(chat_manager, message=prompt_task)
    
    # Ambil output dari agen terakhir (Final_Judge)
    final_response = agent_coordinator.chat_messages[chat_manager][-1]['content']
    
    # Ekstraksi menggunakan Regex untuk menangkap angka saja
    extracted_score = re.search(r'[1-6]', final_response)
    if extracted_score:
        return int(extracted_score.group())
    return 3 # Skor default jika terjadi error format

In [3]:
# Pastikan path direktori sudah benar
train_data = pd.read_csv('../dataset/train.csv').head(5) 

agent_predictions = []

print("Memulai evaluasi Multi-Agent (5 Sampel)...")

for idx, data_row in tqdm(train_data.iterrows(), total=train_data.shape[0]):
    text_essay = data_row['full_text']
    
    # Panggil fungsi diskusi
    assigned_score = execute_agent_debate(text_essay)
    agent_predictions.append(assigned_score)

train_data['multi_agent_pred'] = agent_predictions

print("\n--- Hasil Simulasi ---")
display(train_data[['essay_id', 'score', 'multi_agent_pred']])

Memulai evaluasi Multi-Agent (5 Sampel)...

  0%|          | 0/5 [00:00<?, ?it/s]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

Many people have car where they live. The thing they don't know is that when you use a car alot of thing can happen like you can get in accidet or the smoke that the car has is bad to breath on if someone is walk but in VAUBAN,Germany they dont have that proble because 70 percent of vauban's families do not own cars,and 57 percent sold a car to move there. Street parkig ,driveways and home garages are forbidden on the outskirts of freiburd that near the French and Swiss borders. You probaly won't see a car in Vauban's streets because they are completely "car free" but If some that lives in VAUBAN that owns a car ownership is allowed,but there are only two places that you can park a large garages at the edge of the development,where a car owner buys a space but it not cheap to buy one they sell the space for you car for $40,000 along with a home. The vauban people completed this in 2006 ,they said that this an example of a growing trend in Europe,The untile states and some where else are suburban life from auto use this is called "smart planning". The current efforts to drastically reduce greenhouse gas emissions from tailes the passengee cars are responsible for 12 percent of greenhouse gas emissions in Europe and up to 50 percent in some car intensive in the United States. I honeslty think that good idea that they did that is Vaudan because that makes cities denser and better for walking and in VAUBAN there are 5,500 residents within a rectangular square mile. In the artical David Gold berg said that "All of our development since World war 2 has been centered on the cars,and that will have to change" and i think that was very true what David Gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in VAUBAN so people can see how we really don't need car to go to place from place because we can walk from were we need to go or we can ride bycles with out the use of a car. It good that they are doing that if you thik about your help the earth in way and thats a very good thing to. In the United states ,the Environmental protection Agency is promoting what is called "car reduced"communtunties,and the legislators are starting to act,if cautiously. Maany experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year. In previous bill,80 percent of appropriations have by law gone to highways and only 20 percent to other transports. There many good reason why they should do this.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:21:56] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:21:57] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:21:57] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:22:02] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here is the evaluation and score:

**Evaluation:** The essay has some strengths in terms of its clarity and simplicity, particularly in the introduction and conclusion sections. However, it lacks depth and analysis, with many sentences being quite short and simplistic. Additionally, there are several grammatical errors and inconsistencies throughout the text.

**Score:** 3/6

The essay's main weakness is its lack of substance and analytical thinking. While it touches on some interesting points about Vauban's car-free policy, it does not provide much context or supporting evidence to make a compelling argument. Additionally, the writing is often unclear and lacks precision, making it difficult to follow at times.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:22:18] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:22:18] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:22:18] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Final_Judge

[autogen.oai.client: 05-19 12:22:21] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Final_Judge (to chat_manager):

4

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (d4dcc637-1329-4a80-bed3-09b37fa39e47): Maximum rounds (3) reached

 20%|██        | 1/5 [00:41<02:44, 41.02s/it]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

I am a scientist at NASA that is discussing the "face" on mars. I will be explaining how the "face" is a land form. By sharing my information about this isue i will tell you just that.

First off, how could it be a martions drawing. There is no plant life on mars as of rite now that we know of, which means so far as we know it is not possible for any type of life. That explains how it could not be made by martians. Also why and how would a martion build a face so big. It just does not make any since that a martian did this.

Next, why it is a landform. There are many landforms that are weird here in America, and there is also landforms all around the whole Earth. Many of them look like something we can relate to like a snake a turtle a human... So if there are landforms on earth dont you think landforms are on mars to? Of course! why not? It's just unique that the landform on Mars looks like a human face. Also if there was martians and they were trying to get our attention dont you think we would have saw one by now?

Finaly, why you should listen to me. You should listen to me because i am a member of NASA and i've been dealing with all of this stuff that were talking about and people who say martians did this have no relation with NASA and have never worked with anything to relate to this landform. One last thing is that everyone working at NASA says the same thing i say, that the "face" is just a landform.

To sum all this up the "face" on mars is a landform but others would like to beleive it's a martian sculpture. Which every one that works at NASA says it's a landform and they are all the ones working on the planet and taking pictures.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:22:33] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:22:37] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here is my evaluation:

The essay presents a clear and concise argument about the "face" on Mars being a natural landform, not a Martian creation. The writer effectively uses logical reasoning to dismiss the idea of Martian involvement and provides examples from Earthly landforms to support their claim. However, the writing could be improved with more attention to grammar, spelling, and sentence structure.

Estimate score: 4 out of 6

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:22:50] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:22:50] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:22:50] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Final_Judge

[autogen.oai.client: 05-19 12:22:53] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Final_Judge (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (e2773215-0a8d-4017-bebf-af87b1b5eb43): Maximum rounds (3) reached

 40%|████      | 2/5 [01:12<01:46, 35.61s/it]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

People always wish they had the same technology that they have seen in movies, or the best new piece of technology that is all over social media. However, nobody seems to think of the risks that these kinds of new technologies may have. Cars have been around for many decades, and now manufacturers are starting to get on the bandwagon and come up with the new and improved technology that they hope will appeal to everyone. As of right now, it seems as though the negative characteristics of these cars consume the positive idea that these manufacturers have tried to convey.

Currently, this new technology in cars has a very long way to go before being completely "driverless". Drivers still need to be on alert when they are driving, as well as control the car near any accidents or complicated traffic situations. This seems to totally defeat the purpose of the "driverless" car. Eventually the technology may improve, but nobody can be certain that the driverless car will eventually become completely "driverless". This idea just seems like a lot of hard work and money for something that is not very neccessary. If someone does not want to drive their car they can just take a city bus or a subway. There are so many options of transportation that can already solve this problem. Even if masnufacturers are trying to make driving more "fun", driving is not meant to be "fun" it is meant to get people where they need to go. Playing around in a car just to have "fun" is just a recipe for disaster.

The idea of the driverless car also raises many questions about who will be liable when someone gets into an accident in one of these new cars. Many states do not even let people drive semi-automatic cars because there are not even laws that pertain to the liability of anyone who get into an accident while driving these type of cars. If these cars become more popular, states may pass new laws. However, this topic also raises questions about who is able to dictate whether or not it was the car or the human's fault for an accident. Since this technology is so new, there could be many problems with the car's system that nobody has even discovered since they have not drove the car themselves. If someone test drives this kind of car or even purchases one and they get into a crash not knowing what could possibly happen to them, they will want to sue the car manufacturer since they were not aware of any bugs in the car's system. These lawsuits can add up and eventually the manufactuers will be in a bunch of debt, which could cost them their whole idea of the driverless car.

The technology car manufacturers are trying to develope may just be a diasaster in the making. There are many alternative options of transportations if you do not feel like driving yourself, and these options are way less expensive than buying a brand new car. Although this technology is relatively new, we can not be certain that this new idea will even pay off in the end, it may just be a waste of money and time. Sometimes the newest technology is not the most benefical.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:23:09] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:23:09] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:23:09] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:23:15] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here's my evaluation:

The essay presents a clear argument against the development of driverless cars, highlighting concerns about safety, liability, and the potential for lawsuits. The writer effectively uses examples to illustrate their points, such as the need for human intervention in complex traffic situations. However, the essay could benefit from more nuanced analysis and consideration of counterarguments.

Estimate score: 4 out of 6

The essay demonstrates a good understanding of the topic and presents some strong arguments against driverless cars. The writing is clear and easy to follow, with effective use of transitions between paragraphs. However, the essay could be strengthened by more in-depth analysis and consideration of alternative perspectives. Additionally, some sentences could be tightened up for better clarity and concision. Overall, a solid effort!

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:23:19] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:23:19] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (a61ae773-bb9c-4f90-93d2-86ceb2c1824b): Maximum rounds (3) reached

 60%|██████    | 3/5 [01:39<01:02, 31.41s/it]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

We all heard about Venus, the planet without almost oxygen with earthquakes, erupting volcanoes and temperatures average over 800 degrees Fahrenheit but what if scientist project the futur into this planet ? Through this article, the author uses evidences appealing to reason and concession to make us realize why we should care about studying this planet so that people must give a chance to Venus.

Venus is the closest planet to Earth in terms density and size but has a really different climate. As it is evoked by the author:

( 3) "A thick atmosphere of almost 97 percent carbon dioxide blankets Venus. Even more challenging are the clouds of highly corrosive sulfuric acid in Venus’s atmosphere. On the planet’s surface, temperatures average over 800 degrees Fahrenheit....Beyond high pressure and heat, Venusian geology and weather present additional impediments like erupting volcanoes, powerful earthquakes, and frequent lightning strikes to probes seeking to land on its surface." The author uses of concession tell us what is the actual climate of Venus. He tell us the truth, he support the fact that studying Venus is a worthy pursuit but he also recognize that there's a danger present continuously. And because he support the idea of studying Venus, he proposes ways to study the planet and find a solution at a reasonable distance.

Venus is an inhospitable planet that can almost be considered as an impossible dwelling for humans. But for the author, that can't keep scientist to do their job (studying Venus) : (5) "NASA’s possible solution to the hostile conditions on the surface of Venus would allow scientists to float above the fray. Imagine a blimp-like vehicle hovering 30 or so miles above the roiling Venusian landscape. Just as our jet airplanes travel at a higher altitude to fly over many storms, a vehicle hovering over Venus would avoid the unfriendly ground conditions by staying up and out of their way. At thirty-plus miles above the surface, temperatures would still be toasty at around 170 degrees Fahrenheit, but the air pressure would be close to that of sea level on Earth." Through this evidence, appealing to reasonning, the author talk about the NASA's possible solution to raise his credibility. But also, to convince the audience that we can only find a solution by studying the planet.

In conclusion, despite of Venus hostility put in advance by the concession, the author makes the audience realize that there's a solution but that we can find it only if we study the planet. He make us find out that challenge and curiosity is part of human life. But also that danger and fear should not stop us from discovering new things. After all, we are Humans.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:23:34] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:23:37] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here is my evaluation:

The essay effectively uses concession to present a balanced view of Venus's hostile environment while highlighting the importance of studying the planet. The author's use of evidence and appealing to reason helps to build credibility and convince the audience of the value of exploring Venus.

Estimated score: 5/6

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:23:53] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:23:53] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:23:53] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Final_Judge

[autogen.oai.client: 05-19 12:23:56] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Final_Judge (to chat_manager):

4

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (b0cc6a74-2ab1-451d-9cd6-ed8cdc9d67da): Maximum rounds (3) reached

 80%|████████  | 4/5 [02:15<00:33, 33.48s/it]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

Dear, State Senator

This is a letter to argue in favor of keeping the Electoral College."There are many reasons to keep the Electoral College" one reason is because it is widely regarded as an anachronism, a dispute over the outcome of an Electoral College vote is possible, but it is less likely than a dispute over the popular vote, and the Electoral College restores some of the weight in the political balance that large states (by population) lose by virue of the mal apportionment of the Senate decreed in the Constitution.

I am in favor of keeping the Electoral College because,it is widely regarded as an anachronism. A non-democratic method of selecting a president that ought to be [overruled] by declaring the canaditdate who receives the most populare votes the winner. The advocates of this position are correct in arguing that the Electoral College method is not democratic in a method sense.It is the electors who elect the the president ,not the people. But each party selects a slate of electors trusted to vote for the party's nominee (and that trust is rarely betrayed).

Another, reason I am in favor of keeping the Electoral College is because, a dispute over the outcome of an Electoral College vote is possible. But it is less likely than a dispute over the popular vote. But it is less likely than a dispute over the popular vote. The reason is that the winning canadate's share of the Electoral College invariably exceeds his share of the popular vote.

Last but not least, I am in favor of keeping the Electoral College is because, the Electoral College restores some of the weight in the political balance that large states (by population) lose by virue of the mal apportionment of the Senate decreed in the Constitution. A larger state gets more attintion from presidential canadidates in a campaign than a small state does. It can be argued that Electoral College methods of selecting the president may turn off potential voters for a canadidates who has no hope of carrying their state. But of  course no voter's vote swings a national election, and in spite of that, about 1/2 the eligible American population did vote in the [2012's] election.

From, PROPER_NAME

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:24:09] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:24:09] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:24:09] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:24:15] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here is my evaluation:

The essay presents a clear argument in favor of keeping the Electoral College, citing three main reasons: it is widely regarded as an anachronism, disputes over the outcome are less likely to occur, and it restores balance between large and small states. The writer's points are well-organized and supported with logical reasoning.

Evaluation score: 4 out of 6

The essay has some strengths, such as a clear thesis statement and organized structure. However, the writing could be improved by providing more specific examples to support the arguments and using more precise language (e.g., "mal apportionment" is not clearly defined). Additionally, the conclusion feels abrupt and does not summarize the main points effectively.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:24:30] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:24:33] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (8fde5c53-1e01-4609-9b1f-0e9f367897c2): Maximum rounds (3) reached

100%|██████████| 5/5 [02:52<00:00, 34.53s/it]

--- Hasil Simulasi ---

  essay_id  score  multi_agent_pred
0  000d118      3                 4
1  000fe60      3                 5
2  001ab80      4                 3
3  001bdc0      4                 4
4  002ba53      3                 3

In [4]:
# 1. Load dataset uji
test_data = pd.read_csv('../dataset/test.csv')

final_test_predictions = []

print("Memproses data test Kaggle menggunakan Multi-Agent...")

# 2. Iterasi penilaian
for idx, data_row in tqdm(test_data.iterrows(), total=test_data.shape[0]):
    target_text = data_row['full_text']
    
    # Hitung skor
    final_score = execute_agent_debate(target_text)
    final_test_predictions.append(final_score)

# 3. Bentuk DataFrame sesuai requirement Kaggle
submission_df = pd.DataFrame({
    'essay_id': test_data['essay_id'],
    'score': final_test_predictions
})

# 4. Ekspor hasil
submission_df.to_csv('../outputs/submission_autogen.csv', index=False)

print("\nBerhasil! File 'submission_autogen.csv' siap diunggah ke Kaggle.")
display(submission_df.head())

Memproses data test Kaggle menggunakan Multi-Agent...

  0%|          | 0/3 [00:00<?, ?it/s]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

Many people have car where they live. The thing they don't know is that when you use a car alot of thing can happen like you can get in accidet or the smoke that the car has is bad to breath on if someone is walk but in VAUBAN,Germany they dont have that proble because 70 percent of vauban's families do not own cars,and 57 percent sold a car to move there. Street parkig ,driveways and home garages are forbidden on the outskirts of freiburd that near the French and Swiss borders. You probaly won't see a car in Vauban's streets because they are completely "car free" but If some that lives in VAUBAN that owns a car ownership is allowed,but there are only two places that you can park a large garages at the edge of the development,where a car owner buys a space but it not cheap to buy one they sell the space for you car for $40,000 along with a home. The vauban people completed this in 2006 ,they said that this an example of a growing trend in Europe,The untile states and some where else are suburban life from auto use this is called "smart planning". The current efforts to drastically reduce greenhouse gas emissions from tailes the passengee cars are responsible for 12 percent of greenhouse gas emissions in Europe and up to 50 percent in some car intensive in the United States. I honeslty think that good idea that they did that is Vaudan because that makes cities denser and better for walking and in VAUBAN there are 5,500 residents within a rectangular square mile. In the artical David Gold berg said that "All of our development since World war 2 has been centered on the cars,and that will have to change" and i think that was very true what David Gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in VAUBAN so people can see how we really don't need car to go to place from place because we can walk from were we need to go or we can ride bycles with out the use of a car. It good that they are doing that if you thik about your help the earth in way and thats a very good thing to. In the United states ,the Environmental protection Agency is promoting what is called "car reduced"communtunties,and the legislators are starting to act,if cautiously. Maany experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year. In previous bill,80 percent of appropriations have by law gone to highways and only 20 percent to other transports. There many good reason why they should do this.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:24:48] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:24:49] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:24:49] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:24:54] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here is the evaluation and score:

**Evaluation:** The essay has some strengths in terms of its clarity and coherence, particularly in the introduction and conclusion sections. However, there are significant issues with grammar, punctuation, and sentence structure throughout the text. Additionally, the essay could benefit from more nuanced analysis and supporting evidence to make its points about "smart planning" and reducing greenhouse gas emissions.

**Score:** 3/6

The essay's language is often simple and straightforward, which can be effective in conveying ideas, but it also leads to a lack of sophistication and depth. The writer could improve the essay by providing more context and evidence to support their claims, as well as refining their writing style to make it more engaging and persuasive.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:25:10] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:25:10] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:25:10] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Final_Judge

[autogen.oai.client: 05-19 12:25:13] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Final_Judge (to chat_manager):

4

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (a2ddf067-b6ec-4da6-a469-b3f79123dc57): Maximum rounds (3) reached

 33%|███▎      | 1/3 [00:40<01:20, 40.48s/it]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

I am a scientist at NASA that is discussing the "face" on mars. I will be explaining how the "face" is a land form. By sharing my information about this isue i will tell you just that.

First off, how could it be a martions drawing. There is no plant life on mars as of rite now that we know of, which means so far as we know it is not possible for any type of life. That explains how it could not be made by martians. Also why and how would a martion build a face so big. It just does not make any since that a martian did this.

Next, why it is a landform. There are many landforms that are weird here in America, and there is also landforms all around the whole Earth. Many of them look like something we can relate to like a snake a turtle a human... So if there are landforms on earth dont you think landforms are on mars to? Of course! why not? It's just unique that the landform on Mars looks like a human face. Also if there was martians and they were trying to get our attention dont you think we would have saw one by now?

Finaly, why you should listen to me. You should listen to me because i am a member of NASA and i've been dealing with all of this stuff that were talking about and people who say martians did this have no relation with NASA and have never worked with anything to relate to this landform. One last thing is that everyone working at NASA says the same thing i say, that the "face" is just a landform.

To sum all this up the "face" on mars is a landform but others would like to beleive it's a martian sculpture. Which every one that works at NASA says it's a landform and they are all the ones working on the planet and taking pictures.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:25:24] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:25:29] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here is my evaluation:

The essay presents a clear and concise argument about the "face" on Mars being a natural landform, rather than an artificial Martian sculpture. The writer effectively uses logical reasoning to dismiss the idea of Martian involvement and instead emphasizes the similarities between Earth's landforms and the one on Mars. However, the writing could benefit from improved grammar, spelling, and sentence structure.

Estimate score: 4 out of 6

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:25:42] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:25:42] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:25:42] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Final_Judge

[autogen.oai.client: 05-19 12:25:45] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Final_Judge (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (decd2409-50f0-450e-aae9-42b7acb753b8): Maximum rounds (3) reached

 67%|██████▋   | 2/3 [01:12<00:35, 35.39s/it]

Coordinator (to chat_manager):

Mohon berikan evaluasi dan skor untuk esai berikut:

People always wish they had the same technology that they have seen in movies, or the best new piece of technology that is all over social media. However, nobody seems to think of the risks that these kinds of new technologies may have. Cars have been around for many decades, and now manufacturers are starting to get on the bandwagon and come up with the new and improved technology that they hope will appeal to everyone. As of right now, it seems as though the negative characteristics of these cars consume the positive idea that these manufacturers have tried to convey.

Currently, this new technology in cars has a very long way to go before being completely "driverless". Drivers still need to be on alert when they are driving, as well as control the car near any accidents or complicated traffic situations. This seems to totally defeat the purpose of the "driverless" car. Eventually the technology may improve, but nobody can be certain that the driverless car will eventually become completely "driverless". This idea just seems like a lot of hard work and money for something that is not very neccessary. If someone does not want to drive their car they can just take a city bus or a subway. There are so many options of transportation that can already solve this problem. Even if masnufacturers are trying to make driving more "fun", driving is not meant to be "fun" it is meant to get people where they need to go. Playing around in a car just to have "fun" is just a recipe for disaster.

The idea of the driverless car also raises many questions about who will be liable when someone gets into an accident in one of these new cars. Many states do not even let people drive semi-automatic cars because there are not even laws that pertain to the liability of anyone who get into an accident while driving these type of cars. If these cars become more popular, states may pass new laws. However, this topic also raises questions about who is able to dictate whether or not it was the car or the human's fault for an accident. Since this technology is so new, there could be many problems with the car's system that nobody has even discovered since they have not drove the car themselves. If someone test drives this kind of car or even purchases one and they get into a crash not knowing what could possibly happen to them, they will want to sue the car manufacturer since they were not aware of any bugs in the car's system. These lawsuits can add up and eventually the manufactuers will be in a bunch of debt, which could cost them their whole idea of the driverless car.

The technology car manufacturers are trying to develope may just be a diasaster in the making. There are many alternative options of transportations if you do not feel like driving yourself, and these options are way less expensive than buying a brand new car. Although this technology is relatively new, we can not be certain that this new idea will even pay off in the end, it may just be a waste of money and time. Sometimes the newest technology is not the most benefical.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:26:01] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:26:01] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-19 12:26:02] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:26:07] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):

Here's my evaluation:

The essay presents a clear argument against the development of driverless cars, highlighting concerns about safety, liability, and the potential for lawsuits. The writer effectively uses examples to illustrate their points, such as the need for human intervention in complex traffic situations. However, the essay could benefit from more nuanced analysis and supporting evidence.

Estimated score: 4 out of 6

The essay demonstrates a good understanding of the topic and presents some compelling arguments against driverless cars. The writing is clear and easy to follow, with effective use of transitions between paragraphs. However, the essay could be strengthened by incorporating more specific data or expert opinions to support its claims. Additionally, the conclusion could be more effectively tied back to the thesis statement. Overall, the essay shows promise but needs further development to reach its full potential.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-19 12:26:11] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Primary_Assessor

[autogen.oai.client: 05-19 12:26:11] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Primary_Assessor (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (ef8034b5-eb93-404d-b15c-6bbb60937378): Maximum rounds (3) reached

100%|██████████| 3/3 [01:38<00:00, 32.94s/it]

Berhasil! File 'submission_autogen.csv' siap diunggah ke Kaggle.

  essay_id  score
0  000d118      4
1  000fe60      5
2  001ab80      3